# Site settings
title: Jeff Drocco
description: My webpage
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jeff Drocco
user_description: Cupertino, Notre Dame, Princeton, LANL, LLNL
user_title: Scientist
email: jeff@drocco.org
twitter_username: lorem_ipsum
github_username:  jdrocco
gplus_username:  jdrocco

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
