# Site settings
title: Jeff Drocco
description: My webpage
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jeff Drocco
user_description: Cupertino, Notre Dame, Princeton, LANL, LLNL
user_title: Scientist
email: jdrocco@gmail.com
facebook_username: jeff.drocco
github_username:  jdrocco
linkedin_username:  jeffdrocco

# Google-analytics
google-analytics:
  id: "UA-96997533-1"

exclude: ['package.json', 'src' , 'node_modules']
